apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bigbertha-llmchatbot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/pauldotyu/BigBertha'
    path: llmops
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: chatbotapp.environment.HUGGINGFACEHUB_API_TOKEN
          value: placeholder
        - name: chatbotapp.image.tag
          value: v1.7
        - name: chatbotapp.replicas
          value: '1'
        - name: chatbotapp.resources.memoryLimit
          value: 5Gi
        - name: chatbotapp.resources.memoryRequest
          value: 3Gi
        - name: chatbotapp.image.repository
          value: aishwaryaprabhat/chatbot
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: bigbertha
  syncPolicy:
    syncOptions:
      - CreateNamespace=true