apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.secretName }}
type: Opaque
data:
  accesskey: {{ .Values.minio.accessKey.value | b64enc }}
  secretkey: {{ .Values.minio.secretKey.value | b64enc }}