apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-workflows-role
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflows", "workflowtemplates"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-workflows-binding
subjects:
- kind: ServiceAccount
  name: default  # Replace with the correct service account name
  namespace: {{ .Values.eventbus.namespace }}
roleRef:
  kind: Role
  name: create-workflows-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: vector-ingestion
  name: pod-patcher
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-pods
  namespace: vector-ingestion
subjects:
- kind: ServiceAccount
  name: default
  namespace: vector-ingestion
roleRef:
  kind: Role
  name: pod-patcher
  apiGroup: rbac.authorization.k8s.io
