# templates/service-monitor.yaml
apiVersion: {{ ternary "azmonitoring.coreos.com/v1" "monitoring.coreos.com/v1" .Values.servicemonitor.useAzureServiceMonitor }}
kind: ServiceMonitor
metadata:
  labels:
    isServiceMonitor: "true"
  name: {{ .Release.Name }}-servicemonitor
spec:
  endpoints:
  - port: metricsport
    scheme: http
  namespaceSelector:
    matchNames:
    - {{ .Values.servicemonitor.targetNamespace }}
  selector:
    matchLabels:
      {{- with .Values.servicemonitor.selectorLabels }}
      {{ toYaml . | nindent 8 }}
      {{- end }}